/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EncovaButton {
        "text": string;
    }
}
declare global {
    interface HTMLEncovaButtonElement extends Components.EncovaButton, HTMLStencilElement {
    }
    var HTMLEncovaButtonElement: {
        prototype: HTMLEncovaButtonElement;
        new (): HTMLEncovaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "encova-button": HTMLEncovaButtonElement;
    }
}
declare namespace LocalJSX {
    interface EncovaButton {
        "text"?: string;
    }
    interface IntrinsicElements {
        "encova-button": EncovaButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "encova-button": LocalJSX.EncovaButton & JSXBase.HTMLAttributes<HTMLEncovaButtonElement>;
        }
    }
}
