/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EncovaButton {
        "color": string;
        "disabled": boolean;
        "message": string;
        "text": string;
        "type": string;
    }
    interface EncovaForm {
        "clearField": () => Promise<void>;
    }
    interface EncovaSlat {
        "city": string;
        "coverages": number;
        "insuredName": string;
        "liabilities": object;
        "liabilityNumber": number;
        "limits": object;
        "street": string;
        /**
          * Something that I noticed about props is that when camel casing is used, it sometimes causes an issue in the HTML If you look at the generated readme, it tells you how to use the prop as an attribute
         */
        "vehicle": string;
    }
}
declare global {
    interface HTMLEncovaButtonElement extends Components.EncovaButton, HTMLStencilElement {
    }
    var HTMLEncovaButtonElement: {
        prototype: HTMLEncovaButtonElement;
        new (): HTMLEncovaButtonElement;
    };
    interface HTMLEncovaFormElement extends Components.EncovaForm, HTMLStencilElement {
    }
    var HTMLEncovaFormElement: {
        prototype: HTMLEncovaFormElement;
        new (): HTMLEncovaFormElement;
    };
    interface HTMLEncovaSlatElement extends Components.EncovaSlat, HTMLStencilElement {
    }
    var HTMLEncovaSlatElement: {
        prototype: HTMLEncovaSlatElement;
        new (): HTMLEncovaSlatElement;
    };
    interface HTMLElementTagNameMap {
        "encova-button": HTMLEncovaButtonElement;
        "encova-form": HTMLEncovaFormElement;
        "encova-slat": HTMLEncovaSlatElement;
    }
}
declare namespace LocalJSX {
    interface EncovaButton {
        "color"?: string;
        "disabled"?: boolean;
        "message"?: string;
        "text"?: string;
        "type"?: string;
    }
    interface EncovaForm {
    }
    interface EncovaSlat {
        "city"?: string;
        "coverages"?: number;
        "insuredName"?: string;
        "liabilities"?: object;
        "liabilityNumber"?: number;
        "limits"?: object;
        "street"?: string;
        /**
          * Something that I noticed about props is that when camel casing is used, it sometimes causes an issue in the HTML If you look at the generated readme, it tells you how to use the prop as an attribute
         */
        "vehicle"?: string;
    }
    interface IntrinsicElements {
        "encova-button": EncovaButton;
        "encova-form": EncovaForm;
        "encova-slat": EncovaSlat;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "encova-button": LocalJSX.EncovaButton & JSXBase.HTMLAttributes<HTMLEncovaButtonElement>;
            "encova-form": LocalJSX.EncovaForm & JSXBase.HTMLAttributes<HTMLEncovaFormElement>;
            "encova-slat": LocalJSX.EncovaSlat & JSXBase.HTMLAttributes<HTMLEncovaSlatElement>;
        }
    }
}
